# Generated by Django 4.2.6 on 2023-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_receipe_receipe_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="receipe_image",
        ),
        migrations.AddField(
            model_name="receipe",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
