# Generated by Django 4.2.6 on 2023-10-25 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_remove_receipe_receipe_image_receipe_total"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Receipe",
            new_name="Receipt",
        ),
    ]
