# Generated by Django 4.2.6 on 2023-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_receipt_receipe_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="name",
            field=models.CharField(default="something", max_length=100),
        ),
    ]
